### ISSUE TITLE
Front-end-back-end communication for John's interface 

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#13]
Let's add a list of all apis front-end needs. Each api should be as specific as it can be.
service.js (xdata.js in the main code) at the front-end handles this while at the backend it's handled by ZvBasicAPI.

api function call name: purpose

**Comment by wookhuk** [comment]
I was just about the create this - good call on this thread. I don't have a finalized list but I will start by listing what I had jotted down and needs to be added/fixed and will refine it as I go along.

1.
**getInitialTrends**: when users have only selected the dataset and x, y, z values (sketchpad is currently empty), we need to initialize the graph template with the selected attributes and show them initial representative and outlier trends.
input: dataset, x, y, z
output: xmin, xmax, ymin, ymax, representative trend list, outlier trend list

2.
**getResultsWithSketch**: When the user sketches on the sketchpad, we need to return the results based on the method they have selected.
input: dataset, x, y, z, all other settings, sketchpoints
output: results list

**Comment by wookhuk** [comment]
actually another option is to have modular calls for the backend. So instead of making a single call for 
**getInitialTrends** shown above, the frontend can make separate 3 calls (getRepresentativeTrends, getOutlierTrend, getDataDetails).

1.
**getResults**: Only returns a list of graphs which is a result of a query (sketch or ZQL).

2.
**getRepresentativeTrends**: Only returns representative trends given the dataset, x, y, z. I imagine we will have some other options for the users so they can modify metrics to define their own "representativeness"

3.
**getOutlierTrends**: Only returns outlier trends given the dataset, x, y, z. I imagine we will have some other options for the users so they can define what a outlier is.

4.
**getDataDetails**: When the user is selecting different values of dataset, x, y, or z, we need the min/max values of x and y to initialize the graph template.

**Comment by adityagp** [comment]
I like this. For now, this getRepresentative and getOutlier should instead of expecting x y z should take in an arbitrary list of visualizations (represented as indexed vectors with index indicating the z value) and can be called within getResults or elsewhere. Are we overloading getRepresentative and getOutlier for scatterplot and bar chart as well? @siddta

**Comment by siddta** [comment]
@adityagp: the above changes will be easy to do in the zql backend, the main code currently works on basic constructs like x,y,z and many other variables, all in one object, plus execution at the backend is not done in a completely task agnostic way.

For instance, currently back-end takes a query, fetches the data from roaring, and hands over the data to similarity, rep, scatter, where each one of these process the data in their own way, and convert the results to a list of viz to be sent to the front end.

I was thinking of not adding/changing the formats in the main code, rather we should slowly move towards zql query execution code where even the interface queries are translated into some form of zql. This would automatically handle some of the points you mentioned.

For the release, I feel cleaning up the main code should be good enuf? ZQL migration can happen in parallel, but may take a bit longer.

**Comment by adityagp** [comment]
I don't follow. Is the plan to decouple the execution paradigms for ZQL and the current interface? That's not desirable in the long term, but may be fine for now for the first release.

**Comment by siddta** [comment]
No, I meant execution should be same for both interface and zql, but is not the case currently. I am suggesting we should work on zql backend to make it support interface as well, that would address some of the points you raised earlier. @adityagp

**Comment by adityagp** [comment]
Got it. I think it's fine for the first release.
