### ISSUE TITLE
dynamic_class_aggregations table not generated automatically

### ISSUE THREAD

**Issue by dorisjlee** [zenvisage/zenvisage#146]
dynamic_class_aggregations table is not generated automatically : 
```
Caused by: org.postgresql.util.PSQLException: ERROR: relation "dynamic_class_aggregations" does not exist
  Position: 44
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
```

There seems to be a line that automatically creates the dynamic_class aggregation table already 
does this but it doesn't seem to create the table automatically when @siddta or I tried it (SQLQueryExecutor.java:576-594). If this doesn't work automatically, we should add 

```
CREATE TABLE dynamic_class_aggregations  (Table_Name   TEXT    NOT NULL,  Tag   TEXT  NOT NULL,  Attributes  TEXT   NOT NULL , Ranges   TEXT   NOT NULL, Count    INT  NOT NULL) 
``` 
into the README.

**Comment by superchaoran** [comment]
Fixed by adding in Create table both in README and server startup check.
https://github.com/zenvisage/zenvisage/commit/f9078185b84d1a26d800fe0594bc12cca430aeb5
https://github.com/zenvisage/zenvisage/commit/46f2426b52740145ebc825080fec0cacf38268b1
This will ,
1.help check and create table:dynamic_class_aggregations for current zenvisage developer who use linux command to build and run.
2.help new zenvisage developer to create correct table schema at first place. 

For current eclipse builder, still need to add the table manually by 
```CREATE TABLE dynamic_class_aggregations  (Table_Name   TEXT    NOT NULL,  Tag   TEXT  NOT NULL,  Attributes  TEXT   NOT NULL , Ranges   TEXT   NOT NULL, Count    INT  NOT NULL) ```
