### ISSUE TITLE
Outliers is not shown, and representatives is not shown for the breast cancer dataset

### ISSUE THREAD

**Issue by adityagp** [zenvisage/zenvisage#160]
<img width="1649" alt="screen shot 2017-09-22 at 12 43 12 pm" src="https://user-images.githubusercontent.com/1056605/30757289-bfa48748-9f93-11e7-9f18-afe30786ff63.png">

**Comment by dorisjlee** [comment]
This is because the choice of y-axis is should be expression. chipassoc and diffexp are binary attributes for each gene, not time series. Technically they should be "z" values, but dynamic classes only work if you have them as y variables, so that's why I've set them as y variables.
<img width="1202" alt="screen shot 2017-09-23 at 9 35 19 am" src="https://user-images.githubusercontent.com/5554675/30774064-8c7b92ee-a042-11e7-91c2-918346c31e09.png">

**Comment by adityagp** [comment]
I see. For now, can we pick attributes that are meaningful to display when we select the preloaded dataset?

**Comment by dorisjlee** [comment]
I've now hardcoded the attribute selection for the preloaded dataset in commit [59e16dd](https://github.com/zenvisage/zenvisage/commit/59e16ddd0a33d352b72f371e20f74006b56e4ee1).

**Comment by adityagp** [comment]
Outstanding! Thanks @dorisjlee
