### ISSUE TITLE
Default smoothing

### ISSUE THREAD

**Issue by adityagp** [zenvisage/zenvisage#166]
I think a default Loess smoothing with 0.5 makes for a relatively noise-free experience. 
Should we set it to that in general? Discuss.

**Comment by dorisjlee** [comment]
I don't think we should do this because if a dataset is already fairly clean, then Loess takes time and could also potentially break ([Issue #128](https://github.com/zenvisage/zenvisage/issues/128)). It might also smooth out important outliers. We should provide a "raw" view of the data by default to the user to avoid confusion.

**Comment by adityagp** [comment]
Fair enough. My main concern is if users upload their noisy datasets, they won't be able to make sense of it until they perform smoothing -- but you're right. Let's not do it.
