### ISSUE TITLE
ZQL query Q6 doesnt work when k > 1

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#167]

**Comment by adityagp** [comment]
This is a longer conversation about ZQL semantics: the query executes, but doesn't give the possible desired output, instead opting for a cross-product, correct?

**Comment by siddta** [comment]
Yeah, there is a semantics issue there. However, it should still return the cross-product-based outputs, currently, it's just breaking silently. @eidehua might know why?

**Comment by eidehua** [comment]
Fixed, there was a bug. The current distance process executor does this: 
for each axisvariable
  for each value
    do cross product of the viz that match in f1 and f2

for example,
for axisvariable (state.*)
  for each value (for every state, say NY)
    (compares f1.NY viz with f2.NY viz)

The bug was that the we were using the * itself for matching purposes. So i added code to expand out the * into the actual state values. 


![image](https://user-images.githubusercontent.com/7684873/33861261-88792e4c-dea2-11e7-8bf4-adff88f60b8c.png)
