### ISSUE TITLE
Data upload issues

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#202]
There are quite a few issues here that we need to fix:
- Notify users about data upload failure messages when upload fails at the backend
- Overwrite the file in the target folder if a file with similar name already exists.
- Automatic schema detection is broken: 1) detects floats as int , 2) only maps strings as z attributes

**Comment by dorisjlee** [comment]
Schema autodetect type checking issue resolved by @jaywoo123 in [62acc0](https://github.com/zenvisage/zenvisage/commit/62acc0d10139db96654dca6912f5a30164d75579) and tested. Type issue would not cause failure message because of the hierarchical data type setup. File in target with same name is already overwritten with latest file.
