### ISSUE TITLE
Upload instructions missing

### ISSUE THREAD

**Issue by adityagp** [zenvisage/zenvisage#58]
The dataset upload functionality is great (thx @seanzyx), but we need to standardize the schema and provide a (?) button that clarifies what is expected so that users can upload and play around with their datasets.

**Comment by siddta** [comment]
Yeah, there is a lot of clean-up to be done. We ask users for many things that they don't need. Since a lot of other changes were happening, I didn't want to make bigger changes here.

Also the schema format should be consistent between the inmemdb and postgres. Earlier I was thinking, for postgres, one simple option could have been to let the users give us CREATE table SQL query and INSERT data query and we run it for them, but maybe it's not a good idea. Other than not being consistent with inmemory data loading format, many users might not know how to write such sql queries, so better if we construct these queries ourselves.

I'll soon post here on how cleaned-up schema should like for both dbs.

**Comment by adityagp** [comment]
OK, I don't like the idea of the user providing the SQL, since we're not expecting them to be comfortable with the language. Much easier for them to say: here are the attribs i'm planning to explore for x, and for y, and here are various ways i may group viz. For this, I think something simpler suffices, e.g., first row is 
"x: attrib1, attrib2, ...."
second row is 
"y: attrib1, ..."
third row is 
"z: ..."
then after that it's a csv, with a header.
