### ISSUE TITLE
Next steps for representative trends work

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#9]
So that we can create more concrete issues and assign them to Sean, Sajjadur and me

**Comment by siddta** [comment]
@seanzyx: Could you please add a comment here what you're currently thinking on representative trends? I'll probably have some concrete set of tasks by the end of week.

**Comment by seanzyx** [comment]
So the method I'm currently trying on measuring similarity is to first summarize the given trend into major segments, by setting maximun error and minimum number of segments in the bottom up linear regression process ( I found that this is gives a better summary than using the landmark method ). Usually a trend will be divided into 6 or more line segments.

Then I run DTW to compare the similarity between 2 trends based on their feature segments. It gives pretty reasonable results when I run it with data I read in myself, but not as good when I put it into the zenvisage code. I think this may be due to how the sketched plot is transform into data, like scales or others. I'm currently looking into this, and also trying to adapt the equation of how 2 line segments should be compared.

**Comment by siddta** [comment]
Alright, let's discuss more in the evening. I'd suggest you use two additional datasets along with real estate, because real estate doesn't seem to have a good variety of patterns for us to say anything conclusive about your approach. Which is the other dataset that you mentioned above over which this approach works?

Overall I think the idea of dividing a trend into multiple segments and coming up a with a set of features to characterize each segment is good. We can try  euclidean, euclidean with different weights for each feature, and DTW over the segments.
